export async function GET() {
    return new Response(
        `
        <?xml version="1.0" encoding="UTF-8" ?>
        <urlset
            xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
            xmlns:xhtml="https://www.w3.org/1999/xhtml"
            xmlns:mobile="https://www.google.com/schemas/sitemap-mobile/1.0"
            xmlns:news="https://www.google.com/schemas/sitemap-news/0.9"
            xmlns:image="https://www.google.com/schemas/sitemap-image/1.1"
            xmlns:video="https://www.google.com/schemas/sitemap-video/1.1"
        >
        <url>
        <loc>https://lisaloof.com/</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/ueber-mich</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/hypnose-klagenfurt</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/hypnose-klagenfurt/raucherentwoehnung</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/hypnose-klagenfurt/digital-detox</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/hypnose-klagenfurt/entspannt-in-die-pruefung</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/hypnose-klagenfurt/tiefenentspannung</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/hypnose-klagenfurt/selbstwert-steigern</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/hypnose-klagenfurt/online-hypnose</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/kontakt</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/onlinehypnose</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/impressum</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://lisaloof.com/datenschutz</loc>
        <lastmod>2023-07-29T07:00:09+00:00</lastmod>
        <priority>0.80</priority>
    </url>
        </urlset>`.trim(),
        {
            headers: {
                'Content-Type': 'application/xml'
            }
        }
    );
}